apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-api
  template:
    metadata:
      labels:
        app: stream-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: sql-sa
      containers:
      - name: stream-api-cnt
        image: aksacr1.azurecr.io/api-gateway:latest
        # volumeMounts:
        # - name: secrets-store-inline
        #   mountPath: /data
        
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: DB_SERVER
          value: "sqlserver1n.database.windows.net"
        - name: DB_NAME
          value: "sqldb"
        - name: DB_PORT
          value: "1433"
        # env:
        # - name: APPLICATIONINSIGHTS_CONNECTION_STRING
        #   value: InstrumentationKey=9ade6d8d-7469-4979-9892-4bc1669cbed5;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=874a442b-fa64-45ac-aa9e-1ae530feae69
        # - name: DATABASE_URL
        #   value: Driver={ODBC Driver 18 for SQL Server};Server=tcp:sqlserveraks.database.windows.net,1433;Database=sqlserver;Uid=adminuser;Pwd=admin@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;

      # volumes:
      #   - name: secrets-store-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "my-provider"