apiVersion: v1
kind: ConfigMap
metadata:
  name: stream-config
data:
  DBURL: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:adminsql123.database.windows.net,1433;Database=mssqldb;Uid=adminuser;Pwd=admin@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  JWT_ALGORITHM: "HS256"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=76ed93b5-4511-45f0-bb5f-5f0846720312;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=f3c8463c-d797-495e-b222-b5439f8fc7e5"
  VITE_API_HOST: "https://api.puneetdevops.online"
---
apiVersion: v1
kind: Secret
metadata:
  name: stream-secret
  namespace: default
type: Opaque
stringData:
  JWT_SECRET_KEY: dev-super-secret-jwt-key-change-this-in-production-12345
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-auth
  template:
    metadata:
      labels:
        app: stream-auth
    spec:
      containers:
      - name: stream-auth-cnt
        image: aksacr12.azurecr.io/auth-service:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: stream-config
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stream-secret
              key: JWT_SECRET_KEY
        ports:
        - containerPort: 8001
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: stream-auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP