apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-vault-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-vault
  template:
    metadata:
      labels:
        app: stream-vault
    spec:
      containers:
      - name: stream-vault-cnt
        image: aksacr1.azurecr.io/vault-service:latest
        
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8009
        livenessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: secrets-store-inline
          mountPath: /data
        # env:
        # - name: DATABASE_URL
        #   value: Driver={ODBC Driver 18 for SQL Server};Server=tcp:sqlserveraks.database.windows.net,1433;Database=sqlserver;Uid=adminuser;Pwd=admin@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
        # - name: APPLICATIONINSIGHTS_CONNECTION_STRING
        #   value: InstrumentationKey=9ade6d8d-7469-4979-9892-4bc1669cbed5;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=874a442b-fa64-45ac-aa9e-1ae530feae69
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "my-provider"