apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: zevoryx-instrumentation
  namespace: opentelemetry-operator-system
spec:
  exporter:
    endpoint: https://children-fonts-reflect-cast.trycloudflare.com
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://children-fonts-reflect-cast.trycloudflare.com
      - name: OTEL_BSP_SCHEDULE_DELAY_MILLIS
        value: "200"
      - name: OTEL_BLRP_SCHEDULE_DELAY_MILLIS
        value: "200"
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://children-fonts-reflect-cast.trycloudflare.com
      - name: OTEL_BSP_SCHEDULE_DELAY_MILLIS
        value: "200"
      - name: OTEL_BLRP_SCHEDULE_DELAY_MILLIS
        value: "200"
