# OpenTelemetry Collector Configuration for Zevoryx
image:
  repository: otel/opentelemetry-collector-k8s
  tag: "0.153.0"

mode: daemonset

# Chart presets
presets:
  logsCollection:
    enabled: true
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true

clusterRole:
  rules:
    - apiGroups: ['']
      resources: ['nodes/stats', 'nodes/proxy']
      verbs: ['get']

config:
  receivers:
    file_log:
      include:
        - /var/log/pods/ecomm_*/*/*.log

  processors:
    batch:
      send_batch_size: 50
      timeout: 200ms
    resourcedetection:
      detectors:
        - env
        - system
        - azure

  exporters:
    otlphttp:
      endpoint: "https://management-diana-officers-suzuki.trycloudflare.com"

  service:
    pipelines:
      logs:
        receivers:
          - file_log
        processors:
          - k8s_attributes
          - resourcedetection
          - batch
        exporters:
          - otlphttp
      metrics:
        receivers:
          - hostmetrics
          - kubelet_stats
        processors:
          - resourcedetection
          - batch
        exporters:
          - otlphttp
      traces:
        receivers:
          - otlp
        processors:
          - resourcedetection
          - batch
        exporters:
          - otlphttp
