apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: zevoryx-instrumentation
  namespace: opentelemetry-operator-system
spec:
  exporter:
    endpoint: https://oxford-permanent-var-sunrise.trycloudflare.com
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://oxford-permanent-var-sunrise.trycloudflare.com
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://oxford-permanent-var-sunrise.trycloudflare.com
