apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: zevoryx-instrumentation
  namespace: opentelemetry-operator-system
spec:
  exporter:
    endpoint: http://surveys-castle-workers-beginning.trycloudflare.com:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://surveys-castle-workers-beginning.trycloudflare.com:4318
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://surveys-castle-workers-beginning.trycloudflare.com:4318
